steps:
  - task: UseDotNet@2
    displayName: Use .NET SDK 6.0.201
    inputs:
      packageType: sdk
      version: 6.0.201

  - task: DotNetCoreCLI@2
    displayName: Compile common code and macOS Helpers
    inputs:
      command: build
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Mac$(configuration)'

  - task: DotNetCoreCLI@2
    displayName: Run common unit tests
    inputs:
      command: test
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Mac$(configuration)'
      publishTestResults: true
      testRunTitle: 'Unit tests (macOS)'
