name: Build-Installers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: "Linux Installers"

    runs-on: ubuntu-20.04
    #strategy:
    #  matrix:
    #    os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c release --no-restore src/linux/Payload.Linux/Payload.Linux.csproj
