name: Build-Installers

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: "Linux"

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Install dependencies
      run: dotnet restore --force

    - name: Build Linux Payloads
      run: dotnet build -c Release src/linux/Packaging.Linux/Packaging.Linux.csproj

    - name: Upload Installers
      uses: actions/upload-artifact@v2
      with:
        name: Installers
        path: |
          out/linux/Packaging.Linux/deb/Release/*.deb
          out/linux/Packaging.Linux/tar/Release/*.tar.gz
